#!/bin/bash
#
# 08-start-services.sh - Start all Docker services
# Launches containers and displays status
#
# Usage:
#   ./08-start-services.sh [--json]
#

set -euo pipefail

# Source library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../../lib/init.sh"

# Parse arguments
for arg in "$@"; do
    case $arg in
        --json) OUTPUT_MODE="json" ;;
    esac
done

# ============================================
# HELPER FUNCTIONS
# ============================================

# Create docker-compose.override.yml to disable unused services
create_compose_override() {
    local project_root="$1"

    report_log "info" "Configuring service profiles..."

    cat > "$project_root/docker-compose.override.yml" << 'EOF'
# Auto-generated by setup module
# This file disables optional services using Docker Compose profiles
# Services with profiles won't start unless explicitly enabled

services:
EOF

    # Disable Cloudflare if not configured
    local cf_token
    cf_token=$(get_env_value "CLOUDFLARE_TUNNEL_TOKEN" "$project_root/.env")

    if [[ -z "$cf_token" || "$cf_token" == "your_tunnel_token_here" ]]; then
        cat >> "$project_root/docker-compose.override.yml" << 'EOF'
  # Cloudflare Tunnel - disabled (not configured)
  cloudflared:
    profiles: ["cloudflare"]
EOF
        report_log "info" "Cloudflare Tunnel: disabled"
    else
        report_log "success" "Cloudflare Tunnel: enabled"
    fi
}

# Show access information
show_access_info() {
    local project_root="$1"

    local lan_ip
    lan_ip=$(hostname -I | awk '{print $1}')

    # Check Cloudflare configuration
    local cf_token domain
    cf_token=$(get_env_value "CLOUDFLARE_TUNNEL_TOKEN" "$project_root/.env")
    domain=$(get_env_value "DOMAIN" "$project_root/.env")

    if [[ -n "$cf_token" && "$cf_token" != "your_tunnel_token_here" && -n "$domain" ]]; then
        echo ""
        echo -e "${GREEN}Public Services (via Cloudflare Tunnel):${NC}"
        echo "  Homarr:         https://homarr.${domain}"
        echo "  Jellyfin:       https://jellyfin.${domain}"
        echo "  Jellyseerr:     https://jellyseerr.${domain}"
    fi

    echo ""
    echo -e "${BLUE}All Services (LAN: ${lan_ip}):${NC}"
    echo "  Homarr:         http://${lan_ip}:7575"
    echo "  Jellyfin:       http://${lan_ip}:8096"
    echo "  Jellyseerr:     http://${lan_ip}:5055"
    echo "  Sonarr:         http://${lan_ip}:8989"
    echo "  Radarr:         http://${lan_ip}:7878"
    echo "  Lidarr:         http://${lan_ip}:8686"
    echo "  Prowlarr:       http://${lan_ip}:9696"
    echo "  Bazarr:         http://${lan_ip}:6767"
    echo "  qBittorrent:    http://${lan_ip}:8080"
    echo "  SABnzbd:        http://${lan_ip}:8085"
    echo "  Tdarr:          http://${lan_ip}:8265"
    echo "  ARM:            http://${lan_ip}:8090"
    echo "  Uptime Kuma:    http://${lan_ip}:3001"
}

# ============================================
# MAIN
# ============================================

main() {
    init_progress "Start Services" 4
    local project_root
    project_root=$(get_project_root)

    cd "$project_root"

    # Step 1: Create override file
    report_progress 1 4 "Creating compose override..."

    create_compose_override "$project_root"

    report_progress 1 4 "Override file created" "complete"

    # Step 2: Validate configuration
    report_progress 2 4 "Validating configuration..."

    if ! validate_compose; then
        finish_progress "error" "Configuration validation failed"
        exit 1
    fi

    report_progress 2 4 "Configuration valid" "complete"

    # Step 3: Start services
    report_progress 3 4 "Starting all services..."

    if docker compose up -d; then
        report_progress 3 4 "Services started" "complete"
    else
        report_progress 3 4 "Failed to start some services" "error"
        finish_progress "error" "Service startup failed"
        exit 1
    fi

    # Step 4: Show status
    report_progress 4 4 "Checking service status..."

    # Give services a moment to initialize
    sleep 3

    if [[ "$OUTPUT_MODE" == "json" ]]; then
        local status
        status=$(docker compose ps --format json 2>/dev/null || docker compose ps)
        echo "{\"status\":\"started\",\"containers\":$status}"
    else
        echo ""
        docker compose ps
        echo ""

        show_access_info "$project_root"

        echo ""
        echo -e "${YELLOW}Next Steps:${NC}"
        echo "  1. Wait 2-3 minutes for services to fully initialize"
        echo "  2. Run: ./scripts/configure-services.sh"
        echo "  3. Or run: ./scripts/homelab configure"
        echo ""
        echo -e "${YELLOW}Useful Commands:${NC}"
        echo "  docker compose logs -f       View logs"
        echo "  docker compose down          Stop services"
        echo "  docker compose up -d         Start services"
    fi

    report_progress 4 4 "Status displayed" "complete"

    finish_progress "complete" "All services started successfully"
}

main "$@"
